### PR TITLE
Add nrpe to mirrors

### PR DESCRIPTION
**Pull request by surminus**
We need to be able to monitor disk usage on the mirrors. This commit adds a module and the required check.

### CODE REVIEW

**Comment by surminus** [comment]
Need to update `Puppetfile.lock` still

**Comment by mattbostock** [comment]
Has this been tested in Vagrant?

How will the NRPE commands be authenticated?

**Comment by alexmuller** [comment]
Looks good to me, this runs fine in Vagrant :+1:

I don't have any thoughts on authenticating the NRPE commands but as this change doesn't directly affect that I think this is good to merge.

**Comment by mattbostock** [comment]
@alexmuller The reason I asked about authentication is that this module will configure NRPE on the mirrors, including the `allowed_hosts=` which determines which hosts can issue commands.

I don't think this will work as-is because:

- we haven't opened up the NRPE port in UFW
- `allowed_hosts` isn't set

**Comment by mattbostock** [comment]
I've raised a PR to address these issues:
https://github.com/alphagov/govuk_mirror-puppet/pull/85

**Pull request merged**
