### PR TITLE
Serve assets using new domain

### PR DESCRIPTION
**Pull request by alexmuller**
This domain has changed.

# To do before merging

- [x] Verify that this directory exists on the mirror machine

### CODE REVIEW

**Comment by alexmuller** [comment]
```
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.digital.cabinet-office.gov.uk/ -type f | wc -l
15342
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.publishing.service.gov.uk/ -type f | wc -l
116
```

**Comment by alexmuller** [comment]
```
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.digital.cabinet-office.gov.uk/ -type f | wc -l
15346
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.publishing.service.gov.uk/ -type f | wc -l
190
```

I suppose we could move/copy the old files to the new directory.

**Comment by surminus** [comment]
Agree, copy the files to the new directory if there's space?

**Comment by alexmuller** [comment]
```
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.digital.cabinet-office.gov.uk/ -type f | wc -l
15346
alexmuller@production-mirrorer-1:/mnt/crawler_worker$ find assets.publishing.service.gov.uk/ -type f | wc -l
15350
```

**Comment by surminus** [comment]
:+1: MERGE AND FLY

**Pull request merged**
