### PR TITLE
Remove fail2ban from the govuk_mirror-puppet repo

### PR DESCRIPTION
**Pull request by deanwilson**
After a discussion we no longer want to run Fail2Ban.

https://trello.com/c/7lnrxg1a

### CODE REVIEW

**Comment by deanwilson** [comment]
Force pushed new commit with more details/context from the requesting ticket.

**Comment by surminus** [comment]
:+1: good to merge

**Comment by rjw1** [comment]
probably needs to make the fail2ban package be absent like https://github.com/alphagov/govuk-puppet/pull/4100
although to be honest that can be another pull request or a fabric task in this case.

**Comment by mattbostock** [comment]
@rjw1 I'm going to remove these manually in the interests of getting this deployed.

**Pull request merged**
